# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='project_theme', to='catalogue.ProjectTheme', verbose_name='Theme'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together=set([('primary', 'recommendation')]),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set([('product', 'category')]),
        ),
    ]
